### ISSUE TITLE
StringBuffer - is it null terminated?

### ISSUE THREAD

**Issue by OlHall** [dcs-bios/dcs-bios-arduino-library#11]
Is the string buffer null terminated?

In the example below, the declared string is 4 characters, but does the pointer to newValue point to a 5 char buffer (i.e. 4 data + \0)?

    void onRaltDisplayChange(char* newValue) {
        /* your code here */
    }
    DcsBios::StringBuffer<4> raltDisplayBuffer(0x14aa, onRaltDisplayChange);

**Comment by jboecker** [comment]
The data we get from DCS-BIOS is not null-terminated, but the StringBuffer class allocates one byte more and adds a null terminator so you can just pass `newValue` to functions that want a string, such as `lcd.print()`.

**Comment by OlHall** [comment]
Thanks!
