### ISSUE TITLE
Semanitcs: Should IntegerBuffer be renamed to IntegerData

### ISSUE THREAD

**Issue by OlHall** [dcs-bios/dcs-bios-arduino-library#16]
And the same for the MappedIntegerBuffer that I've proposed.

It's correct for StringBuffer, but I think the integer variant isn't really a buffer, and this would then be consistent with the 'data' member of Integer and MappedInteger.

**Comment by jboecker** [comment]
Future versions of the Arduino library will accept map functions everywhere. The code snippets from the control reference will generate C++11 lambda functions to map the values.
