### ISSUE TITLE
warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

### ISSUE THREAD

**Issue by Hooch234** [dcs-bios/dcs-bios-arduino-library#23]
I have done what the user guide says, but all the input switches do nothing because of this error.  The LED works fine.  Any suggestions?
\Arduino\libraries\dcs-bios-arduino-library-0.1.4\examples\MasterCaution\MasterCaution.ino:8:62: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

 DcsBios::Switch2Pos masterCautionBtn("UFC_MASTER_CAUTION", 10);

Thanks,

Hooch

**Comment by jboecker** [comment]
That's a compiler warning, not an error, and it should not cause anything to go wrong.

When you push the button, do you see a reaction in the command line window of the "connect-to-serial-port.cmd" script? If you have a reaction there, then the Arduino side works and it's probably a network problem (i.e. DCS.exe is not listening for the UDP packets that the script is sending).

Please try the steps in [this post.](http://forums.eagle.ru/showpost.php?p=2535239&postcount=130)
