### ISSUE TITLE
Remove callbacks from ExportStreamListeners

### ISSUE THREAD

**Issue by Gadroc** [dcs-bios/dcs-bios-arduino-library#4]
Currently some of the listeners have callbacks.  These callbacks are called during protocol parsing which is extremely timing sensitive at higher bus speeds.  We should move these out and any code that was executed there should be triggered at end of frame.

**Comment by danvac** [comment]
Is there any guideline how to work with StringBuffers after this change?

**Comment by jboecker** [comment]
I recommend using the release versions. I have not tested the code in the current master branch much, most of my development time has been spent on implementing RS-485 support. When I get that done, I will integrate it and release a new, tested version.

**Comment by jboecker** [comment]
Current versions only copy the data to another buffer during parsing, callbacks are called from DcsBios::loop().
